version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: globant_db
      POSTGRES_USER: globant_user
      POSTGRES_PASSWORD: globant_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U globant_user -d globant_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    restart: always
    environment:
      DATABASE_URL: postgresql://globant_user:globant_pass@db:5432/globant_db
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
